#!/usr/bin/env bash
# codex-three-tier-orchestration: MCP 桥半自动部署（macOS / Linux）
# 流程：预检依赖 → 生成密钥 → 写 start-bridge.local.sh → 启动捕获模式
#      → 用户创建连接器 → 轮询 ngrok API 捕获 client_id/redirect_uri → 回写并收尾。
# 用户全程只需两件事：在 ChatGPT 创建连接器、最后输一次 OAuth 密码。
# 用法: ./setup.sh <ngrok静态域名> <项目路径> [端口]
set -euo pipefail

DOMAIN="${1:?用法: ./setup.sh <ngrok静态域名> <项目路径> [端口]}"
WORKSPACE="${2:?缺少项目路径}"
PORT="${3:-8765}"
BRIDGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_SH="$BRIDGE_DIR/start-bridge.local.sh"
NGROK_API="http://127.0.0.1:4040/api"
TIMEOUT_SEC=600

# 去掉可能的 https:// 前缀与末尾斜杠
DOMAIN="${DOMAIN#https://}"
DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%/}"

rand_str() {  # $1=长度 $2=字符集
  python3 -c "import secrets,sys; s=sys.argv[1]; print(''.join(secrets.choice(s) for _ in range(int(sys.argv[2]))))" "$2" "$1"
}

echo "== codex-three-tier-orchestration MCP bridge setup =="
echo "DOMAIN    = $DOMAIN"
echo "WORKSPACE = $WORKSPACE"
echo "PORT      = $PORT"
echo ""

# ---------- 1. 预检 ----------
if (exec 3<>/dev/tcp/127.0.0.1/"$PORT") 2>/dev/null; then
  exec 3>&- 3<&-
  echo "[stop] 端口 $PORT 已有服务在监听——请先关闭旧的桥再运行本脚本。"
  exit 1
fi

if ! command -v coding-tools-mcp >/dev/null 2>&1; then
  echo "[1/6] 未找到 coding-tools-mcp，尝试 uv tool install..."
  if command -v uv >/dev/null 2>&1; then
    uv tool install coding-tools-mcp
  fi
fi
command -v coding-tools-mcp >/dev/null 2>&1 || { echo "[stop] 装不上。请手动执行: uv tool install coding-tools-mcp"; exit 1; }
echo "[1/6] coding-tools-mcp: $(command -v coding-tools-mcp)"

if ! command -v ngrok >/dev/null 2>&1; then
  echo "[stop] 未找到 ngrok。macOS: brew install ngrok；Linux: 到 ngrok.com 下载。装好后重跑本脚本。"
  exit 1
fi
echo "[2/6] ngrok: $(command -v ngrok)"

ngrok config check >/dev/null 2>&1 || { echo "[stop] ngrok 未配置 authtoken。先执行: ngrok config add-authtoken <你的token>"; exit 1; }
echo "[2/6] ngrok authtoken: OK"

# ---------- 2. 生成密钥 ----------
OAUTH_PASSWORD="$(rand_str 20 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789')"
TOKEN_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
BEARER_TOKEN="$(rand_str 40 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ0123456789')"
echo "[3/6] 密钥已生成（OAuth 密码 / 稳定签名密钥 / Bearer 令牌）"

write_local_sh() {  # $1=client_id $2=redirect_uri
  cat > "$LOCAL_SH" <<EOF
#!/usr/bin/env bash
# GENERATED by setup.sh. Contains secrets. NEVER commit this file.
set -euo pipefail

export CODING_TOOLS_MCP_SERVER_URL="https://$DOMAIN"
export CODING_TOOLS_MCP_OAUTH_PASSWORD="$OAUTH_PASSWORD"
export CODING_TOOLS_MCP_OAUTH_CLIENT_ID="$1"
export CODING_TOOLS_MCP_OAUTH_REDIRECT_URIS="$2"
export CODING_TOOLS_MCP_OAUTH_TOKEN_SECRET="$TOKEN_SECRET"
export CODING_TOOLS_MCP_OAUTH_TOKEN_TTL="604800"

if ! (exec 3<>/dev/tcp/127.0.0.1/$PORT) 2>/dev/null; then
  echo "Starting MCP server (background)..."
  nohup coding-tools-mcp --workspace "$WORKSPACE" --host 127.0.0.1 --port $PORT --auth-token "$BEARER_TOKEN" --oauth-mode > /tmp/coding-tools-mcp.log 2>&1 &
  sleep 8
else
  exec 3>&- 3<&-
  echo "[OK] MCP server already running on port $PORT."
fi

echo "============================================"
echo "  PERMANENT URL: https://$DOMAIN/mcp"
echo "  Keep this window open while using ChatGPT."
echo "  Close it to stop the tunnel (Ctrl+C)."
echo "============================================"

exec ngrok http --url="$DOMAIN" "$PORT"
EOF
  chmod +x "$LOCAL_SH"
}

# ---------- 3. 写启动文件（捕获模式）----------
write_local_sh "__CAPTURE_PENDING__" "__CAPTURE_PENDING__"
echo "[4/6] 已写: $LOCAL_SH"

# ---------- 4. 启动隧道 + 捕获模式服务器 ----------
echo "[5/6] 启动 ngrok 隧道与 MCP 服务器（捕获模式）..."
ngrok http --url="$DOMAIN" "$PORT" > /tmp/clo-ngrok.log 2>&1 &
NGROK_PID=$!
API_UP=false
for _ in $(seq 1 15); do
  sleep 2
  if curl -s --max-time 3 "$NGROK_API/tunnels" >/dev/null 2>&1; then API_UP=true; break; fi
done
if [ "$API_UP" != "true" ]; then
  kill "$NGROK_PID" 2>/dev/null || true
  echo "[stop] ngrok 启动失败。检查：① 域名是否已绑定到你的 ngrok 账号 ② 是否已有另一个 ngrok 在跑（同域名只能一个会话）。"
  exit 1
fi

export CODING_TOOLS_MCP_SERVER_URL="https://$DOMAIN"
export CODING_TOOLS_MCP_OAUTH_PASSWORD="$OAUTH_PASSWORD"
export CODING_TOOLS_MCP_OAUTH_TOKEN_SECRET="$TOKEN_SECRET"
export CODING_TOOLS_MCP_OAUTH_TOKEN_TTL="604800"
nohup coding-tools-mcp --workspace "$WORKSPACE" --host 127.0.0.1 --port "$PORT" --auth-token "$BEARER_TOKEN" --oauth-mode > /tmp/coding-tools-mcp.log 2>&1 &
MCP_PID=$!
sleep 8
if ! (exec 3<>/dev/tcp/127.0.0.1/"$PORT") 2>/dev/null; then
  kill "$MCP_PID" 2>/dev/null || true
  kill "$NGROK_PID" 2>/dev/null || true
  echo "[stop] MCP 服务器未能监听 $PORT。看日志: tail /tmp/coding-tools-mcp.log"
  exit 1
fi
exec 3>&- 3<&-

# ---------- 5. 用户创建连接器 + 轮询捕获 ----------
echo ""
echo "======== 现在需要你操作（全程唯一一次）========"
echo "1. ChatGPT → 新建对话 → 创建 Custom MCP 连接器"
echo "   URL: https://$DOMAIN/mcp"
echo "   认证: OAuth"
echo "2. 授权页若报 Unknown client_id 是预期的（捕获模式），不用管，继续往下"
echo "============================================="
echo "等待连接器请求到达（最长 $((TIMEOUT_SEC / 60)) 分钟）..."

CLIENT_ID=""
REDIRECT_URI=""
DEADLINE=$(( $(date +%s) + TIMEOUT_SEC ))
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
  sleep 4
  CLIENT_ID="$(curl -s --max-time 5 "$NGROK_API/requests/http" | grep -oE 'client_id=[^&" ]+' | head -1 | cut -d= -f2- || true)"
  REDIRECT_URI="$(curl -s --max-time 5 "$NGROK_API/requests/http" | grep -oE 'redirect_uri=[^&" ]+' | head -1 | cut -d= -f2- || true)"
  # URL 解码（仅解 %3A %2F 等常见编码；Python 兜底更稳）
  if [ -n "$CLIENT_ID" ] && [ -n "$REDIRECT_URI" ]; then
    CLIENT_ID="$(python3 -c 'import sys,urllib.parse; print(urllib.parse.unquote(sys.argv[1]))' "$CLIENT_ID")"
    REDIRECT_URI="$(python3 -c 'import sys,urllib.parse; print(urllib.parse.unquote(sys.argv[1]))' "$REDIRECT_URI")"
    break
  fi
done

if [ -z "$CLIENT_ID" ] || [ -z "$REDIRECT_URI" ]; then
  echo ""
  echo "[timeout] 未捕获到连接器参数。手动兜底："
  echo "1. 回 ChatGPT 点连接器「重新连接」→ 浏览器跳到授权页"
  echo "2. 从地址栏复制整个 URL，找 client_id= 和 redirect_uri= 两个参数"
  echo "3. 编辑 $LOCAL_SH，把 __CAPTURE_PENDING__ 替换成这两个值"
  echo "4. 运行 $LOCAL_SH 启动 → 回 ChatGPT 重新连接 → 输密码"
  kill "$MCP_PID" "$NGROK_PID" 2>/dev/null || true
  exit 1
fi

echo "[ok] 已捕获: client_id=$CLIENT_ID"
echo "[ok] 已捕获: redirect_uri=$REDIRECT_URI"

# ---------- 6. 回写并收尾 ----------
write_local_sh "$CLIENT_ID" "$REDIRECT_URI"
kill "$MCP_PID" 2>/dev/null || true
sleep 2
export CODING_TOOLS_MCP_OAUTH_CLIENT_ID="$CLIENT_ID"
export CODING_TOOLS_MCP_OAUTH_REDIRECT_URIS="$REDIRECT_URI"
nohup coding-tools-mcp --workspace "$WORKSPACE" --host 127.0.0.1 --port "$PORT" --auth-token "$BEARER_TOKEN" --oauth-mode > /tmp/coding-tools-mcp.log 2>&1 &
sleep 6
if ! (exec 3<>/dev/tcp/127.0.0.1/"$PORT") 2>/dev/null; then
  echo "[stop] 预注册后重启失败，检查 $LOCAL_SH 里的值是否完整。"
  exit 1
fi
exec 3>&- 3<&-
kill "$MCP_PID" "$NGROK_PID" 2>/dev/null || true

echo ""
echo "======== 部署完成 ========"
echo "1. 运行 $LOCAL_SH 启动桥（以后每天也用它）"
echo "2. 回 ChatGPT 点连接器「重新连接」→ 授权页输 OAuth 密码"
echo "3. 密码: $OAUTH_PASSWORD  （也在 $LOCAL_SH 的 CODING_TOOLS_MCP_OAUTH_PASSWORD 行）"
echo ""
echo "OAuth 三件套已固化进启动文件：重启服务器不再废 token（7 天 TTL，过期重授权一次即可）。"
echo "冒烟测试与排障见 bridge/README.md 与 docs/pitfalls.md。"
