# codex-quota-saver: MCP 桥半自动部署（Windows PowerShell 5.1+）
# 流程：预检依赖 → 生成密钥 → 写 start-bridge.local.bat → 启动捕获模式
#      → 用户创建连接器 → 轮询 ngrok API 捕获 client_id/redirect_uri → 回写并收尾。
# 用户全程只需两件事：在 ChatGPT 创建连接器、最后输一次 OAuth 密码。
# 用法: powershell -ExecutionPolicy Bypass -File .\setup.ps1 -Domain <ngrok静态域名> -Workspace <项目路径> [-Port 8765]
param(
  [Parameter(Mandatory=$true)][string]$Domain,
  [Parameter(Mandatory=$true)][string]$Workspace,
  [int]$Port = 8765
)

$ErrorActionPreference = "Stop"
$BridgeDir = $PSScriptRoot
$LocalBat = Join-Path $BridgeDir "start-bridge.local.bat"
$NgrokApi = "http://127.0.0.1:4040/api"
$TimeoutSec = 600
$McpExe = ""
$NgrokExe = ""

# ---------- helpers ----------
function New-RandomString([int]$Length, [string]$Charset) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $bytes = New-Object byte[] ($Length * 4)
  $rng.GetBytes($bytes)
  $sb = New-Object System.Text.StringBuilder
  foreach ($b in $bytes) {
    if ($sb.Length -ge $Length) { break }
    [void]$sb.Append($Charset[$b % $Charset.Length])
  }
  return $sb.ToString()
}

function New-RandomHex([int]$Bytes) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $buf = New-Object byte[] $Bytes
  $rng.GetBytes($buf)
  return (-join ($buf | ForEach-Object { $_.ToString("x2") }))
}

function Find-Tool([string]$Name, [string]$FallbackPath) {
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  if ($FallbackPath -ne "" -and (Test-Path $FallbackPath)) { return $FallbackPath }
  return ""
}

function Find-Ngrok {
  $cmd = Get-Command "ngrok" -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  # winget 把 ngrok 装在版本化路径里，通常不在 PATH 上——通配找
  $wingetDir = Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Packages"
  if (Test-Path $wingetDir) {
    $found = Get-ChildItem -Path $wingetDir -Recurse -Filter "ngrok.exe" -ErrorAction SilentlyContinue |
      Where-Object { $_.FullName -like "*Ngrok.Ngrok*" } | Select-Object -First 1
    if ($found) { return $found.FullName }
  }
  # 手动安装的常见位置
  $manual = Join-Path $env:LOCALAPPDATA "ngrok\ngrok.exe"
  if (Test-Path $manual) { return $manual }
  return ""
}

function Write-LocalBat([string]$ClientId, [string]$RedirectUri) {
  # 生成文件全 ASCII（坑：.bat 内非 ASCII 会乱码破坏解析）
  $content = "@echo off`r`n" +
    "title Coding Tools MCP - ChatGPT Connector (local)`r`n" +
    "REM ==== GENERATED by setup.ps1. Contains secrets. NEVER commit this file. ====`r`n`r`n" +
    "set CODING_TOOLS_MCP_SERVER_URL=https://$Domain`r`n" +
    "set CODING_TOOLS_MCP_OAUTH_PASSWORD=$OAuthPassword`r`n" +
    "set CODING_TOOLS_MCP_OAUTH_CLIENT_ID=$ClientId`r`n" +
    "set CODING_TOOLS_MCP_OAUTH_REDIRECT_URIS=$RedirectUri`r`n" +
    "set CODING_TOOLS_MCP_OAUTH_TOKEN_SECRET=$TokenSecret`r`n" +
    "set CODING_TOOLS_MCP_OAUTH_TOKEN_TTL=604800`r`n`r`n" +
    "netstat -ano | findstr `":$Port`" | findstr `"LISTENING`" >nul`r`n" +
    "if %errorlevel%==0 (`r`n" +
    "    echo [OK] MCP server already running on port $Port.`r`n" +
    ") else (`r`n" +
    "    echo Starting MCP server...`r`n" +
    "    start `"MCP Server`" /min `"$McpExe`" --workspace `"$Workspace`" --host 127.0.0.1 --port $Port --auth-token $BearerToken --oauth-mode`r`n" +
    "    timeout /t 8 /nobreak >nul`r`n" +
    ")`r`n`r`n" +
    "echo.`r`n" +
    "echo   PERMANENT URL: https://$Domain/mcp`r`n" +
    "echo   Keep this window open while using ChatGPT.`r`n" +
    "echo   Close it to stop the tunnel.`r`n" +
    "echo.`r`n`r`n" +
    "`"$NgrokExe`" http --url=$Domain $Port`r`n" +
    "pause`r`n"
  [System.IO.File]::WriteAllText($LocalBat, $content, (New-Object System.Text.ASCIIEncoding))
}

function Stop-ServerOnPort {
  $rows = netstat -ano | Select-String ":$Port\s" | Select-String "LISTENING"
  foreach ($row in $rows) {
    $parts = ($row.ToString() -split "\s+") | Where-Object { $_ -ne "" }
    $pidToKill = $parts[$parts.Length - 1]
    if ($pidToKill -match "^\d+$") {
      Stop-Process -Id ([int]$pidToKill) -Force -ErrorAction SilentlyContinue
    }
  }
}

# ---------- 0. 参数整理 ----------
if ($Domain -match "^https?://") { $Domain = ($Domain -replace "^https?://", "") }
$Domain = $Domain.TrimEnd("/")

Write-Host "== codex-quota-saver MCP bridge setup =="
Write-Host "DOMAIN    = $Domain"
Write-Host "WORKSPACE = $Workspace"
Write-Host "PORT      = $Port"
Write-Host ""

# ---------- 1. 预检 ----------
$listening = netstat -ano | Select-String ":$Port\s" | Select-String "LISTENING"
if ($listening) {
  Write-Host "[stop] 端口 $Port 已有服务在监听——请先关闭旧的桥再运行本脚本（避免两台服务器混用）。" -ForegroundColor Red
  exit 1
}

if (-not (Test-Path $Workspace)) {
  Write-Host "[stop] 工作区路径不存在: $Workspace（必须是一个真实存在的仓库目录）" -ForegroundColor Red
  exit 1
}

$McpExe = Find-Tool "coding-tools-mcp" (Join-Path $env:USERPROFILE ".local\bin\coding-tools-mcp.exe")
if ($McpExe -eq "") {
  Write-Host "[1/6] 未找到 coding-tools-mcp，尝试 uv tool install..."
  $uv = Get-Command "uv" -ErrorAction SilentlyContinue
  if ($uv) {
    & uv tool install coding-tools-mcp | Out-Null
    $McpExe = Find-Tool "coding-tools-mcp" (Join-Path $env:USERPROFILE ".local\bin\coding-tools-mcp.exe")
  }
  if ($McpExe -eq "") {
    Write-Host "[stop] 装不上。请手动执行: uv tool install coding-tools-mcp （无 uv 则先装 uv: https://docs.astral.sh/uv/）" -ForegroundColor Red
    exit 1
  }
}
Write-Host "[1/6] coding-tools-mcp: $McpExe"

$NgrokExe = Find-Ngrok
if ($NgrokExe -eq "") {
  Write-Host "[2/6] 未找到 ngrok，尝试 winget install..."
  winget install --id Ngrok.Ngrok -e --accept-package-agreements --accept-source-agreements 2>$null | Out-Null
  $NgrokExe = Find-Ngrok
}
if ($NgrokExe -eq "") {
  Write-Host "[stop] ngrok 不可用。可能原因：安装失败，或 Defender 把 ngrok.exe 隔离了（先给安装目录加排除项再重装，再重跑本脚本）。" -ForegroundColor Red
  exit 1
}
Write-Host "[2/6] ngrok: $NgrokExe"

& $NgrokExe config check *> $null
if ($LASTEXITCODE -ne 0) {
  Write-Host "[stop] ngrok 未配置 authtoken。先执行: ngrok config add-authtoken <你的token>（ngrok 控制台可查）" -ForegroundColor Red
  exit 1
}
Write-Host "[2/6] ngrok authtoken: OK"

# ---------- 2. 生成密钥 ----------
$OAuthPassword = New-RandomString 20 "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789"
$TokenSecret = New-RandomHex 32
$BearerToken = New-RandomString 40 "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ0123456789"
Write-Host "[3/6] 密钥已生成（OAuth 密码 / 稳定签名密钥 / Bearer 令牌）"

# ---------- 3. 写启动文件（捕获模式：client_id/redirect_uri 暂为占位）----------
Write-LocalBat "__CAPTURE_PENDING__" "__CAPTURE_PENDING__"
Write-Host "[4/6] 已写: $LocalBat"

# ---------- 4. 启动隧道 + 捕获模式服务器 ----------
Write-Host "[5/6] 启动 ngrok 隧道与 MCP 服务器（捕获模式）..."
$ngrokProc = Start-Process $NgrokExe -ArgumentList @("http", "--url=$Domain", [string]$Port) -WindowStyle Minimized -PassThru
$tunnelUp = $false
for ($i = 0; $i -lt 15; $i++) {
  Start-Sleep -Seconds 2
  try {
    $tuns = Invoke-RestMethod -Uri "$NgrokApi/tunnels" -TimeoutSec 3
    foreach ($t in $tuns.tunnels) {
      if ([string]$t.public_url -like "*$Domain*") { $tunnelUp = $true; break }
    }
  } catch { }
  if ($tunnelUp) { break }
}
if (-not $tunnelUp) {
  Stop-Process -Id $ngrokProc.Id -Force -ErrorAction SilentlyContinue
  Write-Host "[stop] ngrok 隧道未建立。检查：① 域名是否已绑定到你的 ngrok 账号（控制台 → Domains）② 是否已有另一个 ngrok 在跑（一个账号同域名只能一个会话）。修正后重跑本脚本。" -ForegroundColor Red
  exit 1
}

$env:CODING_TOOLS_MCP_SERVER_URL = "https://$Domain"
$env:CODING_TOOLS_MCP_OAUTH_PASSWORD = $OAuthPassword
$env:CODING_TOOLS_MCP_OAUTH_TOKEN_SECRET = $TokenSecret
$env:CODING_TOOLS_MCP_OAUTH_TOKEN_TTL = "604800"
# 捕获模式：不预注册 client（这正是要捕获的参数）
$argsStr = "--workspace `"$Workspace`" --host 127.0.0.1 --port $Port --auth-token $BearerToken --oauth-mode"
$mcpProc = Start-Process $McpExe -ArgumentList $argsStr -WindowStyle Minimized -PassThru
Start-Sleep -Seconds 8
$up = netstat -ano | Select-String ":$Port\s" | Select-String "LISTENING"
if (-not $up) {
  Stop-Process -Id $mcpProc.Id -Force -ErrorAction SilentlyContinue
  Stop-Process -Id $ngrokProc.Id -Force -ErrorAction SilentlyContinue
  Write-Host "[stop] MCP 服务器未能监听 $Port。手动运行以下命令看报错：" -ForegroundColor Red
  Write-Host "  $McpExe --workspace `"$Workspace`" --host 127.0.0.1 --port $Port --auth-token $BearerToken --oauth-mode"
  exit 1
}

# ---------- 5. 用户创建连接器 + 轮询捕获 ----------
Write-Host ""
Write-Host "======== 现在需要你操作（全程唯一一次）========" -ForegroundColor Cyan
Write-Host "1. ChatGPT → 新建对话 → 创建 Custom MCP 连接器"
Write-Host "   URL: https://$Domain/mcp"
Write-Host "   认证: OAuth"
Write-Host "2. 授权页若报 Unknown client_id 是预期的（捕获模式），不用管，继续往下"
Write-Host "============================================="
Write-Host "等待连接器请求到达（最长 $($TimeoutSec / 60) 分钟）..."

$deadline = (Get-Date).AddSeconds($TimeoutSec)
$clientId = ""
$redirectUri = ""
while ((Get-Date) -lt $deadline) {
  Start-Sleep -Seconds 4
  try {
    $resp = Invoke-RestMethod -Uri "$NgrokApi/requests/http" -TimeoutSec 5
    foreach ($r in $resp.requests) {
      $uri = [string]$r.request.uri
      if ($uri -match "[?&]client_id=([^&]+)") {
        $clientId = [System.Uri]::UnescapeDataString($Matches[1])
      }
      if ($uri -match "[?&]redirect_uri=([^&]+)") {
        $redirectUri = [System.Uri]::UnescapeDataString($Matches[1])
      }
      if ($clientId -ne "" -and $redirectUri -ne "") { break }
    }
  } catch { }
  if ($clientId -ne "" -and $redirectUri -ne "") { break }
}

if ($clientId -eq "" -or $redirectUri -eq "") {
  Write-Host ""
  Write-Host "[timeout] 未捕获到连接器参数。手动兜底：" -ForegroundColor Yellow
  Write-Host "1. 回 ChatGPT 点连接器「重新连接」→ 浏览器跳到授权页"
  Write-Host "2. 从地址栏复制整个 URL，找 client_id= 和 redirect_uri= 两个参数"
  Write-Host "3. 用记事本打开 $LocalBat，把 __CAPTURE_PENDING__ 替换成这两个值"
  Write-Host "4. 双击 $LocalBat 启动 → 回 ChatGPT 重新连接 → 输密码"
  Stop-ServerOnPort
  Stop-Process -Id $ngrokProc.Id -Force -ErrorAction SilentlyContinue
  exit 1
}

Write-Host "[ok] 已捕获: client_id=$clientId"
Write-Host "[ok] 已捕获: redirect_uri=$redirectUri"

# ---------- 6. 回写并收尾 ----------
Write-LocalBat $clientId $redirectUri
Stop-ServerOnPort
Start-Sleep -Seconds 2
$env:CODING_TOOLS_MCP_OAUTH_CLIENT_ID = $clientId
$env:CODING_TOOLS_MCP_OAUTH_REDIRECT_URIS = $redirectUri
$mcpProc2 = Start-Process $McpExe -ArgumentList $argsStr -WindowStyle Minimized -PassThru
Start-Sleep -Seconds 6
$up2 = netstat -ano | Select-String ":$Port\s" | Select-String "LISTENING"
if (-not $up2) {
  Write-Host "[stop] 预注册后重启失败，检查 $LocalBat 里的值是否完整。" -ForegroundColor Red
  exit 1
}
Stop-ServerOnPort
Stop-Process -Id $ngrokProc.Id -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "======== 部署完成 ========" -ForegroundColor Green
Write-Host "1. 双击 $LocalBat 启动桥（以后每天也用它）"
Write-Host "2. 回 ChatGPT 点连接器「重新连接」→ 授权页输 OAuth 密码"
Write-Host "3. 密码: $OAuthPassword  （也在 $LocalBat 的 CODING_TOOLS_MCP_OAUTH_PASSWORD 行）"
Write-Host ""
Write-Host "OAuth 三件套已固化进启动文件：重启服务器不再废 token（7 天 TTL，过期重授权一次即可）。"
Write-Host "冒烟测试与排障见 bridge/README.md 与 docs/pitfalls.md。"
